// Seeds the global RAG knowledge base — financial planning rules, Indian
// tax law summaries (FY2025-26), IRDAI/SEBI guidelines. Reviewed-content
// model per SRS §12.4: every doc carries a source tag and effective date.
import { pool } from './index';
import { seedGlobalKnowledge } from '../services/rag';

const KB = [
  // ── Tax (IT Act FY2025-26) ───────────────────────────────────────
  { kind: 'tax', source_tag: 'IT Act FY2025-26', title: 'New tax regime slabs FY2025-26', content: 'New regime slabs: income up to ₹4L nil; ₹4–8L at 5%; ₹8–12L at 10%; ₹12–16L at 15%; ₹16–20L at 20%; ₹20–24L at 25%; above ₹24L at 30%. Standard deduction ₹75,000 for salaried. Section 87A rebate makes tax zero for taxable income up to ₹12L. Health & education cess 4% applies on tax.' },
  { kind: 'tax', source_tag: 'IT Act FY2025-26', title: 'Old tax regime slabs and deductions', content: 'Old regime slabs: up to ₹2.5L nil; ₹2.5–5L at 5%; ₹5–10L at 20%; above ₹10L at 30%. Standard deduction ₹50,000. The old regime allows deductions: 80C up to ₹1.5L, 80CCD(1B) NPS ₹50,000, 80D health premiums, 24(b) home loan interest up to ₹2L, HRA exemption. Choose old regime when total deductions are large enough to beat the new regime\'s lower rates — the crossover is typically around ₹3.75L–₹4.5L of deductions depending on income.' },
  { kind: 'tax', source_tag: 'IT Act FY2025-26', title: 'Section 80C qualifying investments', content: 'Section 80C limit is ₹1,50,000 per FY. Qualifying: EPF employee contribution (automatic from salary), PPF, ELSS mutual funds (3-year lock-in), NSC, 5-year tax-saver FD, life insurance premium, home loan principal repayment, children\'s school tuition fees, Sukanya Samriddhi. EPF often fills most of the limit for higher earners — check before adding ELSS purely for tax.' },
  { kind: 'tax', source_tag: 'IT Act FY2025-26', title: 'Section 80D health insurance deduction', content: '80D allows ₹25,000 for self/spouse/children health premiums (₹50,000 if self is a senior citizen), plus a separate ₹25,000 for parents\' premiums (₹50,000 if parents are senior citizens). Preventive health checkups count up to ₹5,000 within the limit. Available only under the old regime.' },
  { kind: 'tax', source_tag: 'IT Act FY2025-26', title: 'NPS additional deduction 80CCD(1B)', content: 'Section 80CCD(1B) gives an additional ₹50,000 deduction for NPS Tier-1 contributions, over and above the 80C limit — old regime only. Employer NPS contributions under 80CCD(2) (up to 10% of basic, 14% for new regime) are deductible in BOTH regimes, making employer NPS one of the few tax shelters that survives the new regime.' },
  { kind: 'tax', source_tag: 'IT Act FY2025-26', title: 'HRA exemption calculation', content: 'HRA exemption is the minimum of: (1) actual HRA received, (2) rent paid minus 10% of basic salary, (3) 50% of basic for metro cities or 40% for non-metro. Old regime only. Rent receipts and landlord PAN (if rent exceeds ₹1L/year) are required as proof.' },
  { kind: 'tax', source_tag: 'IT Act FY2025-26', title: 'Capital gains tax on equity', content: 'Equity LTCG (held >1 year): 12.5% on gains above ₹1.25L per year. STCG (held <1 year): 20%. Equity mutual funds follow the same rules. Tax-loss harvesting before March 31 can offset gains. Debt funds bought after April 2023 are taxed at slab rates regardless of holding period.' },
  { kind: 'tax', source_tag: 'IT Act FY2025-26', title: 'RSU and ESOP taxation', content: 'RSUs are taxed twice: at vesting, the full market value is a perquisite taxed at your slab rate (TDS by employer); at sale, gains over the vesting price are capital gains — LTCG 12.5% if held >2 years for foreign-listed shares (>1 year for Indian-listed). Foreign RSUs must be declared in Schedule FA of the ITR. ESOPs are taxed at exercise (perquisite on FMV minus exercise price) and at sale.' },
  { kind: 'tax', source_tag: 'IT Act FY2025-26', title: 'ITR filing deadlines and advance tax', content: 'ITR filing deadline for salaried: July 31. Advance tax applies when non-TDS tax liability exceeds ₹10,000/year — instalments due June 15 (15%), Sept 15 (45%), Dec 15 (75%), March 15 (100%). Interest under 234B/234C applies on shortfalls. Investment proofs go to your employer by Jan–Feb to avoid excess TDS.' },
  { kind: 'tax', source_tag: 'IT Act FY2025-26', title: 'Section 87A rebate explained', content: 'The 87A rebate makes your tax zero below a threshold. Under the new regime for FY2025-26, taxable income up to ₹12L pays no tax after rebate (₹12.75L for salaried after the ₹75,000 standard deduction). Under the old regime, the rebate applies only up to ₹5L taxable income. The rebate does not apply to special-rate income like capital gains. This is why most people earning up to ~₹12.75L pay no income tax under the new regime.' },
  { kind: 'tax', source_tag: 'IT Act FY2025-26', title: 'Section 80E education loan interest', content: 'Interest on an education loan (for self, spouse, children or a student you are guardian of) is fully deductible under Section 80E with no upper limit, for up to 8 assessment years from when repayment starts. Only the interest qualifies, not the principal. Old regime only. The loan must be from a recognised financial institution or approved charitable trust.' },
  { kind: 'tax', source_tag: 'IT Act FY2025-26', title: 'Section 80G donation deduction', content: 'Donations to eligible funds/institutions are deductible under 80G — some at 100% (e.g. PM National Relief Fund), most at 50%, sometimes subject to a 10%-of-adjusted-income ceiling. You need a stamped receipt with the institution\'s 80G registration number and PAN. Cash donations above ₹2,000 do not qualify — pay digitally. Old regime only.' },
  { kind: 'tax', source_tag: 'IT Act FY2025-26', title: 'Section 80TTA and 80TTB interest deductions', content: '80TTA allows up to ₹10,000 deduction on savings-account interest for those under 60. Senior citizens instead get 80TTB: up to ₹50,000 on all interest (savings + fixed deposits). Both are old-regime only. Interest beyond these limits is taxed at slab rate, and banks deduct TDS on FD interest above ₹40,000 (₹50,000 for seniors) unless you submit Form 15G/15H.' },
  { kind: 'tax', source_tag: 'IT Act FY2025-26', title: 'Form 16, 26AS and AIS reconciliation', content: 'Form 16 is your employer\'s TDS certificate (Part A: tax deducted; Part B: salary breakup). Form 26AS and the Annual Information Statement (AIS) on the income-tax portal show all tax credited against your PAN plus reported income (salary, interest, dividends, share sales, large transactions). Always reconcile your ITR against 26AS/AIS before filing — mismatches are the top trigger for notices. Report income even if no TDS was deducted.' },
  { kind: 'tax', source_tag: 'IT Act FY2025-26', title: 'Gratuity and leave encashment exemptions', content: 'Gratuity received on leaving a job is exempt up to ₹20L (lifetime, for covered private employees). Leave encashment at retirement/resignation is exempt up to ₹25L for non-government employees. These exemptions reduce the taxable portion of your final settlement — check them when you change jobs. Notice-pay recovery and joining bonuses, by contrast, are usually fully taxable.' },
  { kind: 'tax', source_tag: 'IT Act FY2025-26', title: 'Presumptive taxation for freelancers (44ADA/44AD)', content: 'Professionals (consultants, designers, doctors, etc.) with receipts up to ₹75L can use Section 44ADA: 50% of receipts is deemed income, no books needed (limit applies when cash receipts are under 5%). Small businesses use 44AD: 6% of digital turnover (8% cash) up to ₹3Cr is deemed profit. This drastically simplifies tax for gig/freelance income — file ITR-4. You can still be better off declaring actual lower profit, but then audit/bookkeeping rules apply.' },

  // ── Investing basics (SEBI investor education / AMFI) ─────────────
  { kind: 'investing', source_tag: 'AMFI investor education', title: 'Index funds vs active funds', content: 'An index fund simply mirrors a benchmark (e.g. Nifty 50) at very low cost; an active fund pays a manager to try to beat it. Over long periods most active large-cap funds in India have struggled to beat their index after fees. For beginners, a low-cost broad-market index fund is a sensible core. This is category education, not a recommendation of any specific scheme.' },
  { kind: 'investing', source_tag: 'AMFI investor education', title: 'Expense ratio and direct vs regular plans', content: 'The expense ratio is the annual fee a mutual fund charges, deducted daily from NAV. A "direct" plan has no distributor commission and a lower expense ratio than the "regular" plan of the same scheme — over 20 years that gap can mean lakhs of difference on the same fund. Buy direct plans through the AMC or a fee-only platform if you are choosing funds yourself. Always check the expense ratio before investing.' },
  { kind: 'investing', source_tag: 'SEBI investor education', title: 'The major asset classes', content: 'The main asset classes are equity (ownership in companies — high long-run return, high short-term volatility), debt (loans/bonds/FDs — steady, lower return), gold (an inflation/uncertainty hedge), real estate (illiquid, large ticket), and cash/liquid (safety and access). Diversifying across classes that don\'t move together smooths your overall journey. Your mix should follow your goal horizon and risk tolerance, not market hype.' },
  { kind: 'investing', source_tag: 'SEBI investor education', title: 'Diversification and not timing the market', content: 'Spreading money across asset classes and many securities reduces the damage any single failure can do. Trying to time the market — selling out and buying back at the "right" moment — fails for most investors because the best market days cluster near the worst ones. Time in the market beats timing the market. A disciplined monthly investment through ups and downs is the proven approach for ordinary investors.' },
  { kind: 'investing', source_tag: 'AMFI investor education', title: 'SIP vs lumpsum', content: 'A SIP invests a fixed sum monthly, averaging your purchase price and removing the urge to time markets. A lumpsum invests everything at once — statistically better when markets only rise, but riskier if you invest right before a fall. For salaried earners investing from monthly income, SIP is the natural fit. If you receive a windfall, you can stagger it over a few months (a "STP") to reduce timing risk.' },
  { kind: 'investing', source_tag: 'SEBI investor education', title: 'The power of compounding', content: 'Compounding means your returns earn returns. ₹10,000/month at 12% becomes about ₹23L in 10 years, ₹1Cr in ~21 years, and ₹3.5Cr in 30 years — most of the growth arrives in the final years, which is why starting early matters far more than investing large amounts later. Delaying a 10-year head start can roughly halve your final corpus for the same monthly amount.' },
  { kind: 'investing', source_tag: 'SEBI investor education', title: 'KYC and the risk-o-meter', content: 'You complete KYC once (PAN, Aadhaar, address) to invest in mutual funds, and a demat account to hold shares/ETFs. Every mutual fund displays a "risk-o-meter" from Low to Very High — match it to your goal horizon (short-term money should not sit in Very High risk funds). Be wary of any "guaranteed" market-linked return or unsolicited tips: SEBI-registered advice is accountable; anonymous tips are not.' },
  { kind: 'investing', source_tag: 'AMFI investor education', title: 'Debt fund categories and their risks', content: 'Debt funds lend money and carry two main risks: interest-rate risk (prices fall when rates rise — larger for long-duration funds) and credit risk (a borrower defaulting). For parking short-term money, overnight and liquid funds are the lowest-risk options. Money you may need within a year should avoid long-duration or credit-risk funds. Since April 2023, debt-fund gains are taxed at your slab rate regardless of holding period.' },

  // ── Retirement & government schemes (PFRDA / EPFO) ────────────────
  { kind: 'planning', source_tag: 'PFRDA / NPS', title: 'How NPS works', content: 'The National Pension System (NPS) is a low-cost retirement account. Tier-1 is the retirement account (locked till 60); Tier-2 is a flexible add-on. At 60 you can withdraw up to 60% as a tax-free lumpsum; the remaining 40% must buy an annuity (pension), which is taxable as income. You choose equity/debt allocation (Auto or Active mode). Extra tax benefit: ₹50,000 under 80CCD(1B), plus employer contributions under 80CCD(2) that survive even the new regime.' },
  { kind: 'planning', source_tag: 'EPFO', title: 'EPF, EPS and VPF basics', content: 'From salary, 12% of basic goes to your EPF and 12% from the employer (part of which funds the EPS pension). EPF currently earns a government-set rate (~8%+), is EEE (tax-free) if you stay 5+ years, and is one of the best debt instruments available to salaried Indians. You can boost it via VPF (Voluntary PF) at the same rate. Always transfer your EPF when you switch jobs (via the UAN portal) rather than withdrawing — withdrawing before 5 years is taxable and breaks compounding.' },
  { kind: 'planning', source_tag: 'Standard planning rule', title: 'PPF and small-savings schemes', content: 'PPF is a 15-year, government-backed, fully tax-free (EEE) account allowing up to ₹1.5L/year, with a government-set rate revised quarterly (~7.1%). It is ideal long-term debt for the risk-averse and qualifies for 80C. Other small-savings options: Sukanya Samriddhi (for a girl child, higher rate), NSC and 5-year tax-saver FDs (80C), and SCSS for senior citizens. Rates are set by the government each quarter.' },

  // ── Money management & credit (RBI financial education) ───────────
  { kind: 'planning', source_tag: 'RBI financial education', title: 'The 50/30/20 budgeting rule', content: 'A simple starting budget: 50% of take-home for needs (rent, food, EMIs, utilities), 30% for wants (dining, travel, subscriptions), 20% for savings and investments. Automate the 20% on salary day so you save before you spend ("pay yourself first"). Adjust the ratios to your reality, but treat the savings slice as a fixed bill, not whatever is left over.' },
  { kind: 'planning', source_tag: 'RBI financial education', title: 'Credit score (CIBIL) basics', content: 'Your credit score (300–900; 750+ is good) reflects how reliably you repay. The biggest factors: paying every EMI and credit-card bill on time, keeping credit-card usage below ~30% of the limit, not applying for many loans at once, and maintaining a long, clean history. Check your report yearly for errors. A strong score lowers your future loan interest rates — a direct saving worth lakhs over a home loan.' },
  { kind: 'planning', source_tag: 'RBI financial education', title: 'Inflation erodes idle cash', content: 'At ~6% inflation, money sitting in a savings account earning ~3% loses about 3% of its purchasing power every year — ₹1L today buys roughly ₹74,000 worth of goods in 10 years. Keep only your emergency fund and near-term needs in low-yield savings; everything with a 5+ year horizon needs growth assets to stay ahead of inflation. Doing "nothing" with cash is itself a risk.' },
  { kind: 'planning', source_tag: 'Standard planning rule', title: 'First-job money checklist', content: 'New earners, in order: (1) open a salary account and complete KYC; (2) build a 3-month emergency fund; (3) get health insurance (or confirm you are on a family/employer policy); (4) start a small SIP into a broad index fund to build the habit; (5) understand your payslip — basic, HRA, EPF, TDS; (6) avoid lifestyle inflation and EMIs on depreciating things. Time, not income, is a young investor\'s biggest advantage.' },

  // ── Consumer protection & fraud (RBI / DPDP) ─────────────────────
  { kind: 'regulatory', source_tag: 'RBI consumer protection', title: 'Fraud awareness: never share OTP/credentials', content: 'No genuine bank, insurer or government body will ever ask for your OTP, PIN, CVV, or full card number over a call, SMS or link. Treat unsolicited "KYC update", "refund", or "account blocked" messages as fraud. Use official apps and type URLs yourself rather than clicking links. If defrauded, report immediately on the national cybercrime helpline 1930 and to your bank — speed improves recovery odds.' },
  { kind: 'regulatory', source_tag: 'DPDP Act 2023', title: 'Your data rights and grievance redressal', content: 'Under India\'s data-protection law you can access, correct and erase the personal data a company holds about you, and withdraw consent. Reputable apps publish a privacy notice and name a grievance officer who must respond within set timelines. For unresolved financial complaints you can escalate to the relevant ombudsman (RBI for banks, IRDAI for insurers, SEBI SCORES for investments). Keep records of your complaints.' },

  // ── Insurance (IRDAI guideline / Standard planning rule) ─────────
  { kind: 'insurance', source_tag: 'Standard planning rule', title: 'Term insurance sizing: 25x income', content: 'Recommended term life cover is 25× annual income, adjusted upward for outstanding loans and number of dependents. Buy pure term insurance only — endowment, money-back and ULIP plans mix insurance with investment and do both poorly. Term premiums for a healthy 30-year-old run roughly ₹900–1,300 per ₹1L of cover per year for a ₹1Cr policy.' },
  { kind: 'insurance', source_tag: 'IRDAI guideline', title: 'Health insurance: floater and top-up structure', content: 'A family floater of at least ₹10L is the baseline for a Tier-1 city family of four. The most premium-efficient way to raise cover is a super top-up policy (e.g. ₹90L cover above a ₹10L deductible costs a fraction of a ₹1Cr base policy). Employer group cover ends when you leave the job — personal base cover protects against a gap when you are older and premiums are higher or pre-existing conditions apply. Watch for room-rent sub-limits in older policies: a 1% room-rent cap can proportionally reduce the entire claim.' },
  { kind: 'insurance', source_tag: 'IRDAI guideline', title: 'Free look period and claim settlement', content: 'Every insurance policy has a 30-day free-look period (IRDAI mandate) during which you can return it for a refund. Before buying, check the insurer\'s claim settlement ratio (published annually by IRDAI) and the incurred claims ratio for health insurers. Disclose all pre-existing conditions honestly — non-disclosure is the single biggest cause of claim rejection.' },
  { kind: 'insurance', source_tag: 'Standard planning rule', title: 'Insurance products to avoid for wealth building', content: 'Endowment plans, money-back plans and ULIPs typically return 4–6% annually — below inflation — while bundling inadequate life cover. The standard alternative: buy pure term insurance for protection and invest the premium difference in index funds or PPF. Surrendering an old endowment may make sense if the surrender value plus future premiums redirected to better instruments beats holding to maturity; calculate before deciding.' },

  // ── Planning rules ────────────────────────────────────────────────
  { kind: 'planning', source_tag: 'Standard planning rule', title: 'Emergency fund sizing', content: 'Hold 6 months of expenses (3 months minimum) in liquid instruments: savings account plus liquid mutual funds. Single-income households with dependents should target 9–12 months. The emergency fund comes BEFORE investing — it prevents forced borrowing or selling investments in a downturn.' },
  { kind: 'planning', source_tag: 'Standard planning rule', title: 'Asset allocation by age', content: 'A common starting rule: equity percentage ≈ 100 minus age (a 30-year-old holds ~70% equity). Rebalance annually. Direct new contributions to the underweight asset class rather than selling — selling triggers capital gains tax. EPF/PPF/NPS count as debt allocation; many salaried Indians are more debt-heavy than they realise once EPF is counted.' },
  { kind: 'planning', source_tag: 'Standard planning rule', title: 'Prepay loan vs invest framework', content: 'Compare the post-tax loan cost against expected post-tax investment returns. Home loan at 8.5% with 24(b) deduction costs ~6% effective in the 30% bracket; long-run equity index returns average 11–12% (volatile, not guaranteed). Mathematically investing wins, but prepayment is a guaranteed risk-free return and reduces fixed obligations. Common approach: split surplus 50:50 until EMI-to-income is below 30%, then tilt to investing. Always clear credit card debt (36–42% interest) and personal loans (11–16%) before either.' },
  { kind: 'planning', source_tag: 'Standard planning rule', title: 'Debt repayment ordering', content: 'Pay off debts in order of interest rate (avalanche method): credit cards (36–42%) first, then personal loans (11–16%), car loans (9–11%), education loans (8–11%, but interest is tax-deductible under 80E), home loans last (8–9%, tax-advantaged). The snowball method (smallest balance first) trades some maths for motivation — fine if it keeps you consistent. EMIs should stay below 40% of take-home.' },
  { kind: 'planning', source_tag: 'Standard planning rule', title: 'SIP and rupee cost averaging', content: 'A SIP (systematic investment plan) invests a fixed amount monthly, buying more units when markets fall. Increase your SIP by 10% each year as income grows (step-up SIP) — this roughly doubles the final corpus over 20 years versus a flat SIP. For goals under 3 years use debt/liquid funds; 3–7 years hybrid; beyond 7 years equity-heavy.' },
  { kind: 'planning', source_tag: 'Standard planning rule', title: 'Child education corpus planning', content: 'Education costs inflate at ~8–10%/year — double general inflation. A ₹25L course today costs ~₹55L in 10 years at 8%. Start an equity-heavy SIP early, then glide to debt in the final 3 years before the goal. At 12% expected return, reaching ₹50L in 12 years needs roughly ₹15,500/month.' },
  { kind: 'planning', source_tag: 'Standard planning rule', title: 'Retirement corpus rule of thumb', content: 'Target corpus ≈ 25–30× annual expenses at retirement (4% safe withdrawal adapted for India: 3.5% is safer given inflation). A 30-year-old spending ₹50K/month needs ₹6–8Cr at 60 (inflation-adjusted). EPF alone is rarely enough — supplement with NPS and equity index funds. Starting at 30 vs 40 roughly halves the required monthly saving.' },
  { kind: 'planning', source_tag: 'Standard planning rule', title: 'Estate basics: nominations and will', content: 'Nomination is NOT inheritance — a nominee is a trustee for legal heirs. Update nominations on EPF (e-nomination on EPFO portal), bank accounts, mutual funds (via RTA), NPS, and insurance. A will overrides nomination disputes; registration is optional but strengthens it. Without a will, succession law (Hindu Succession Act / Indian Succession Act) decides distribution — often not what the family expects.' },

  // ── Regulatory positioning (SEBI / compliance) ────────────────────
  { kind: 'regulatory', source_tag: 'SEBI IA Regulations 2013', title: 'What financial apps can and cannot advise', content: 'Recommending specific securities (a named stock or mutual fund scheme) for compensation requires SEBI Registered Investment Adviser (RIA) registration. Financial education, organising a user\'s own data, calculating gaps against published standards, and category-level guidance ("increase term cover", "consider a liquid fund for idle cash") do not require RIA registration. PayWatch operates in the education/organisation space and always discloses this.' },
  { kind: 'regulatory', source_tag: 'RBI AA Framework', title: 'Account Aggregator data rights', content: 'The AA framework (RBI-regulated) lets you share financial data via explicit, granular, time-bound, revocable consent. No screen scraping, no credential sharing. You can revoke consent at any time from the AA app or from PayWatch settings, after which AA-sourced data is deleted within 24 hours. Data flows encrypted end-to-end from the bank to the app.' },
];

async function main() {
  const added = await seedGlobalKnowledge(KB);
  console.log(`✓ Knowledge base: ${KB.length} docs total, ${added} newly added (existing ones refreshed)`);
  await pool.end();
}

main().catch((e) => { console.error(e); process.exit(1); });
