// Seeds the global RAG knowledge base — financial planning rules, Indian
// tax law summaries (FY2025-26), IRDAI/SEBI guidelines. Reviewed-content
// model per SRS §12.4: every doc carries a source tag and effective date.
import { pool } from './index';
import { seedGlobalKnowledge } from '../services/rag';

const KB = [
  // ── Tax (IT Act FY2025-26) ───────────────────────────────────────
  { kind: 'tax', source_tag: 'IT Act FY2025-26', title: 'New tax regime slabs FY2025-26', content: 'New regime slabs: income up to ₹4L nil; ₹4–8L at 5%; ₹8–12L at 10%; ₹12–16L at 15%; ₹16–20L at 20%; ₹20–24L at 25%; above ₹24L at 30%. Standard deduction ₹75,000 for salaried. Section 87A rebate makes tax zero for taxable income up to ₹12L. Health & education cess 4% applies on tax.' },
  { kind: 'tax', source_tag: 'IT Act FY2025-26', title: 'Old tax regime slabs and deductions', content: 'Old regime slabs: up to ₹2.5L nil; ₹2.5–5L at 5%; ₹5–10L at 20%; above ₹10L at 30%. Standard deduction ₹50,000. The old regime allows deductions: 80C up to ₹1.5L, 80CCD(1B) NPS ₹50,000, 80D health premiums, 24(b) home loan interest up to ₹2L, HRA exemption. Choose old regime when total deductions are large enough to beat the new regime\'s lower rates — the crossover is typically around ₹3.75L–₹4.5L of deductions depending on income.' },
  { kind: 'tax', source_tag: 'IT Act FY2025-26', title: 'Section 80C qualifying investments', content: 'Section 80C limit is ₹1,50,000 per FY. Qualifying: EPF employee contribution (automatic from salary), PPF, ELSS mutual funds (3-year lock-in), NSC, 5-year tax-saver FD, life insurance premium, home loan principal repayment, children\'s school tuition fees, Sukanya Samriddhi. EPF often fills most of the limit for higher earners — check before adding ELSS purely for tax.' },
  { kind: 'tax', source_tag: 'IT Act FY2025-26', title: 'Section 80D health insurance deduction', content: '80D allows ₹25,000 for self/spouse/children health premiums (₹50,000 if self is a senior citizen), plus a separate ₹25,000 for parents\' premiums (₹50,000 if parents are senior citizens). Preventive health checkups count up to ₹5,000 within the limit. Available only under the old regime.' },
  { kind: 'tax', source_tag: 'IT Act FY2025-26', title: 'NPS additional deduction 80CCD(1B)', content: 'Section 80CCD(1B) gives an additional ₹50,000 deduction for NPS Tier-1 contributions, over and above the 80C limit — old regime only. Employer NPS contributions under 80CCD(2) (up to 10% of basic, 14% for new regime) are deductible in BOTH regimes, making employer NPS one of the few tax shelters that survives the new regime.' },
  { kind: 'tax', source_tag: 'IT Act FY2025-26', title: 'HRA exemption calculation', content: 'HRA exemption is the minimum of: (1) actual HRA received, (2) rent paid minus 10% of basic salary, (3) 50% of basic for metro cities or 40% for non-metro. Old regime only. Rent receipts and landlord PAN (if rent exceeds ₹1L/year) are required as proof.' },
  { kind: 'tax', source_tag: 'IT Act FY2025-26', title: 'Capital gains tax on equity', content: 'Equity LTCG (held >1 year): 12.5% on gains above ₹1.25L per year. STCG (held <1 year): 20%. Equity mutual funds follow the same rules. Tax-loss harvesting before March 31 can offset gains. Debt funds bought after April 2023 are taxed at slab rates regardless of holding period.' },
  { kind: 'tax', source_tag: 'IT Act FY2025-26', title: 'RSU and ESOP taxation', content: 'RSUs are taxed twice: at vesting, the full market value is a perquisite taxed at your slab rate (TDS by employer); at sale, gains over the vesting price are capital gains — LTCG 12.5% if held >2 years for foreign-listed shares (>1 year for Indian-listed). Foreign RSUs must be declared in Schedule FA of the ITR. ESOPs are taxed at exercise (perquisite on FMV minus exercise price) and at sale.' },
  { kind: 'tax', source_tag: 'IT Act FY2025-26', title: 'ITR filing deadlines and advance tax', content: 'ITR filing deadline for salaried: July 31. Advance tax applies when non-TDS tax liability exceeds ₹10,000/year — instalments due June 15 (15%), Sept 15 (45%), Dec 15 (75%), March 15 (100%). Interest under 234B/234C applies on shortfalls. Investment proofs go to your employer by Jan–Feb to avoid excess TDS.' },

  // ── Insurance (IRDAI guideline / Standard planning rule) ─────────
  { kind: 'insurance', source_tag: 'Standard planning rule', title: 'Term insurance sizing: 25x income', content: 'Recommended term life cover is 25× annual income, adjusted upward for outstanding loans and number of dependents. Buy pure term insurance only — endowment, money-back and ULIP plans mix insurance with investment and do both poorly. Term premiums for a healthy 30-year-old run roughly ₹900–1,300 per ₹1L of cover per year for a ₹1Cr policy.' },
  { kind: 'insurance', source_tag: 'IRDAI guideline', title: 'Health insurance: floater and top-up structure', content: 'A family floater of at least ₹10L is the baseline for a Tier-1 city family of four. The most premium-efficient way to raise cover is a super top-up policy (e.g. ₹90L cover above a ₹10L deductible costs a fraction of a ₹1Cr base policy). Employer group cover ends when you leave the job — personal base cover protects against a gap when you are older and premiums are higher or pre-existing conditions apply. Watch for room-rent sub-limits in older policies: a 1% room-rent cap can proportionally reduce the entire claim.' },
  { kind: 'insurance', source_tag: 'IRDAI guideline', title: 'Free look period and claim settlement', content: 'Every insurance policy has a 30-day free-look period (IRDAI mandate) during which you can return it for a refund. Before buying, check the insurer\'s claim settlement ratio (published annually by IRDAI) and the incurred claims ratio for health insurers. Disclose all pre-existing conditions honestly — non-disclosure is the single biggest cause of claim rejection.' },
  { kind: 'insurance', source_tag: 'Standard planning rule', title: 'Insurance products to avoid for wealth building', content: 'Endowment plans, money-back plans and ULIPs typically return 4–6% annually — below inflation — while bundling inadequate life cover. The standard alternative: buy pure term insurance for protection and invest the premium difference in index funds or PPF. Surrendering an old endowment may make sense if the surrender value plus future premiums redirected to better instruments beats holding to maturity; calculate before deciding.' },

  // ── Planning rules ────────────────────────────────────────────────
  { kind: 'planning', source_tag: 'Standard planning rule', title: 'Emergency fund sizing', content: 'Hold 6 months of expenses (3 months minimum) in liquid instruments: savings account plus liquid mutual funds. Single-income households with dependents should target 9–12 months. The emergency fund comes BEFORE investing — it prevents forced borrowing or selling investments in a downturn.' },
  { kind: 'planning', source_tag: 'Standard planning rule', title: 'Asset allocation by age', content: 'A common starting rule: equity percentage ≈ 100 minus age (a 30-year-old holds ~70% equity). Rebalance annually. Direct new contributions to the underweight asset class rather than selling — selling triggers capital gains tax. EPF/PPF/NPS count as debt allocation; many salaried Indians are more debt-heavy than they realise once EPF is counted.' },
  { kind: 'planning', source_tag: 'Standard planning rule', title: 'Prepay loan vs invest framework', content: 'Compare the post-tax loan cost against expected post-tax investment returns. Home loan at 8.5% with 24(b) deduction costs ~6% effective in the 30% bracket; long-run equity index returns average 11–12% (volatile, not guaranteed). Mathematically investing wins, but prepayment is a guaranteed risk-free return and reduces fixed obligations. Common approach: split surplus 50:50 until EMI-to-income is below 30%, then tilt to investing. Always clear credit card debt (36–42% interest) and personal loans (11–16%) before either.' },
  { kind: 'planning', source_tag: 'Standard planning rule', title: 'Debt repayment ordering', content: 'Pay off debts in order of interest rate (avalanche method): credit cards (36–42%) first, then personal loans (11–16%), car loans (9–11%), education loans (8–11%, but interest is tax-deductible under 80E), home loans last (8–9%, tax-advantaged). The snowball method (smallest balance first) trades some maths for motivation — fine if it keeps you consistent. EMIs should stay below 40% of take-home.' },
  { kind: 'planning', source_tag: 'Standard planning rule', title: 'SIP and rupee cost averaging', content: 'A SIP (systematic investment plan) invests a fixed amount monthly, buying more units when markets fall. Increase your SIP by 10% each year as income grows (step-up SIP) — this roughly doubles the final corpus over 20 years versus a flat SIP. For goals under 3 years use debt/liquid funds; 3–7 years hybrid; beyond 7 years equity-heavy.' },
  { kind: 'planning', source_tag: 'Standard planning rule', title: 'Child education corpus planning', content: 'Education costs inflate at ~8–10%/year — double general inflation. A ₹25L course today costs ~₹55L in 10 years at 8%. Start an equity-heavy SIP early, then glide to debt in the final 3 years before the goal. At 12% expected return, reaching ₹50L in 12 years needs roughly ₹15,500/month.' },
  { kind: 'planning', source_tag: 'Standard planning rule', title: 'Retirement corpus rule of thumb', content: 'Target corpus ≈ 25–30× annual expenses at retirement (4% safe withdrawal adapted for India: 3.5% is safer given inflation). A 30-year-old spending ₹50K/month needs ₹6–8Cr at 60 (inflation-adjusted). EPF alone is rarely enough — supplement with NPS and equity index funds. Starting at 30 vs 40 roughly halves the required monthly saving.' },
  { kind: 'planning', source_tag: 'Standard planning rule', title: 'Estate basics: nominations and will', content: 'Nomination is NOT inheritance — a nominee is a trustee for legal heirs. Update nominations on EPF (e-nomination on EPFO portal), bank accounts, mutual funds (via RTA), NPS, and insurance. A will overrides nomination disputes; registration is optional but strengthens it. Without a will, succession law (Hindu Succession Act / Indian Succession Act) decides distribution — often not what the family expects.' },

  // ── Regulatory positioning (SEBI / compliance) ────────────────────
  { kind: 'regulatory', source_tag: 'SEBI IA Regulations 2013', title: 'What financial apps can and cannot advise', content: 'Recommending specific securities (a named stock or mutual fund scheme) for compensation requires SEBI Registered Investment Adviser (RIA) registration. Financial education, organising a user\'s own data, calculating gaps against published standards, and category-level guidance ("increase term cover", "consider a liquid fund for idle cash") do not require RIA registration. PayWatch operates in the education/organisation space and always discloses this.' },
  { kind: 'regulatory', source_tag: 'RBI AA Framework', title: 'Account Aggregator data rights', content: 'The AA framework (RBI-regulated) lets you share financial data via explicit, granular, time-bound, revocable consent. No screen scraping, no credential sharing. You can revoke consent at any time from the AA app or from PayWatch settings, after which AA-sourced data is deleted within 24 hours. Data flows encrypted end-to-end from the bank to the app.' },
];

async function main() {
  const seeded = await seedGlobalKnowledge(KB);
  console.log(seeded ? `✓ Seeded ${KB.length} knowledge base documents` : '· Knowledge base already seeded, skipping');
  await pool.end();
}

main().catch((e) => { console.error(e); process.exit(1); });
