'use client';

import { useEffect, useState } from 'react';
import { get } from '@/lib/api';
import { inr } from '@/lib/format';

// A formal, printable net-worth statement — the kind people need for visa, loan
// or rental applications. Built from the user's own profile data (self-declared).
export default function NetWorthStatementPage() {
  const [nw, setNw] = useState<any>(null);
  const [user, setUser] = useState<any>(null);

  useEffect(() => {
    get('/networth').then(setNw).catch(() => {});
    get('/user/me').then(setUser).catch(() => {});
  }, []);

  if (!nw || !user) return <div className="card h-96 animate-pulse mt-4" />;
  const today = new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' });

  return (
    <div className="space-y-5 max-w-2xl">
      <div className="flex gap-2 no-print">
        <button onClick={() => window.print()} className="btn-primary">Print / Save as PDF</button>
      </div>

      <div className="card p-8">
        <div className="text-center border-b border-paper-200 pb-4 mb-5">
          <h1 className="font-display text-2xl font-semibold">Statement of Net Worth</h1>
          <p className="text-sm text-ink-soft mt-1">{user.name || user.mobile} · as on {today}</p>
        </div>

        <h2 className="text-sm font-bold uppercase tracking-widest text-ink-faint mb-2">Assets</h2>
        <table className="w-full text-sm mb-5">
          <tbody>
            {nw.assets.map((a: any) => (
              <tr key={a.label} className="border-b border-paper-100"><td className="py-2">{a.label}</td><td className="py-2 text-right tabular-nums">{inr(a.value)}</td></tr>
            ))}
            <tr className="font-semibold"><td className="py-2">Total assets</td><td className="py-2 text-right tabular-nums">{inr(nw.totalAssets)}</td></tr>
          </tbody>
        </table>

        <h2 className="text-sm font-bold uppercase tracking-widest text-ink-faint mb-2">Liabilities</h2>
        <table className="w-full text-sm mb-5">
          <tbody>
            {nw.liabilities.length === 0 && <tr><td className="py-2 text-ink-soft">None</td><td /></tr>}
            {nw.liabilities.map((l: any) => (
              <tr key={l.label} className="border-b border-paper-100"><td className="py-2">{l.label}</td><td className="py-2 text-right tabular-nums">{inr(l.value)}</td></tr>
            ))}
            <tr className="font-semibold"><td className="py-2">Total liabilities</td><td className="py-2 text-right tabular-nums">{inr(nw.totalLiabilities)}</td></tr>
          </tbody>
        </table>

        <div className="flex justify-between items-center border-t-2 border-ink pt-3">
          <span className="font-display text-lg font-semibold">Net Worth</span>
          <span className="font-display text-lg font-semibold tabular-nums">{inr(nw.netWorth)}</span>
        </div>

        <div className="mt-10 flex justify-between items-end text-sm">
          <p className="text-ink-faint text-xs">Generated by PayWatch on {today}</p>
          <div className="text-center"><div className="w-44 border-b border-ink-faint mb-1" /><p className="text-xs text-ink-faint">Signature</p></div>
        </div>
        <p className="text-[10px] text-ink-faint mt-6 leading-relaxed">This statement is compiled from self-declared figures provided by the individual and is for personal/informational use. It is not an audited or CA-certified statement.</p>
      </div>
    </div>
  );
}
