export const metadata = { title: 'Regulatory Disclosures' };

export default function Disclosures() {
  return (
    <>
      <h1>Regulatory Disclosures</h1>
      <p>Last updated: June 2026</p>

      <h2>What PayWatch is</h2>
      <p>
        PayWatch is a financial education, organisation and planning tool. We consolidate the financial
        data you already own, calculate scores and gaps using publicly available financial planning standards,
        and suggest categories of action — such as &ldquo;increase your term insurance cover&rdquo; or
        &ldquo;use your remaining Section 80C limit&rdquo;.
      </p>

      <h2>What PayWatch is not</h2>
      <p>
        PayWatch is <strong>not</strong> a SEBI-registered Investment Adviser (RIA), research analyst,
        stock broker, or portfolio manager. We do not recommend specific securities, stocks, or mutual fund
        schemes, and our AI assistant is technically prevented from doing so. Nothing in the app constitutes
        investment advice under the SEBI (Investment Advisers) Regulations, 2013. For personalised investment
        advice, consult a SEBI Registered Investment Adviser; for tax filing, consult a Chartered Accountant.
      </p>

      <h2>AI-generated content</h2>
      <p>
        Answers from &ldquo;Ask Your CFO&rdquo; are generated by an AI system grounded in your financial data
        and a curated knowledge base of Indian tax law, IRDAI guidelines and standard planning rules. Every
        answer carries source tags and a disclaimer. On CFO and Family plans, answers containing
        recommendation-like content are flagged for review by a licensed financial professional. AI output can
        contain errors — verify significant decisions independently.
      </p>

      <h2>Referral commissions</h2>
      <p>
        Where the app links to third-party platforms for insurance or investments, we may earn a referral
        commission (under an AMFI ARN for mutual fund platforms and IRDAI POSP registration for insurance).
        Any such link is explicitly labelled inside the app before you click it. Commission relationships
        never change the substance of our analysis, which is computed from rule-based benchmarks.
      </p>

      <h2>Data and the Account Aggregator framework</h2>
      <p>
        Bank data is accessed exclusively through the RBI-regulated Account Aggregator framework with your
        explicit, granular, time-bound and revocable consent. We never ask for, see, or store bank credentials.
        Revoking consent deletes AA-sourced data within 24 hours.
      </p>

      <h2>Calculations and estimates</h2>
      <p>
        Money Health Scores, tax estimates, projections and premium estimates are computed from your inputs
        and standard assumptions, and are provided for planning purposes only. They are not guarantees.
        Tax calculations follow FY2025-26 law and are updated after each Finance Act.
      </p>

      <h2>Grievances</h2>
      <p>
        Grievance Officer: grievance@paywatch.in. We acknowledge complaints within 48 hours and resolve
        within 30 days, in line with the IT (Intermediary Guidelines) Rules, 2021 and the DPDP Act, 2023.
      </p>
    </>
  );
}
